### ISSUE TITLE
Hi-res timestamps causes failures

### ISSUE THREAD

**Issue by gvanem** [merbanan/rtl_433_tests#254]
Not sure which patch caused this fail. But e.g. a `py -2 bin\run_test.py -C -c ..\rtl_433.exe acuri*`:
```
## Failed: F:\gv\dx-radio\RTL_433\rtl_433_tests\tests\acurite\08\ext-lowbattery.cu8:
{ 'values_changed': { "root[0]['time']": { 'new_value': u'@0.044108s',
                                           'old_value': u'@0.000000s'}}}
...
```

It seems the previous coarse time-stamp (on Windows at-least) has caused these diffs. Since the first timestamp is now at `0.044108s`. Not at `0.000000s` as *expected*.

Where are Travis / AppVeyor when you need them?

**Comment by zuckschwerdt** [comment]
Actually the `makefile` will run
```
python bin/run_test.py -I time --first-line
```
thus ignoring the time stamps ;)

**Comment by gvanem** [comment]
That makes even more errors. `py -2 bin\run_test.py -c ..\rtl_433.exe -I time --first-line acuri*`:
```
## Failed: F:\gv\dx-radio\RTL_433\rtl_433_tests\tests\acurite\08\ext-lowbattery.cu8: invalid json output
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
## Failed: F:\gv\dx-radio\RTL_433\rtl_433_tests\tests\acurite\08\ext-lowbattery.cu8: invalid json output
time      : @0.044108s
```
But adding a `-c NUL` (or `-c /dev/null` for non-Windows) to the  `args`, makes it perfect. 

Thanks for clearing that up.

**Comment by zuckschwerdt** [comment]
If you have default config files for rtl_433 installed that might indeed mess with the tests script.
A short form to disable config files is  `-c 0`.

**Comment by gvanem** [comment]
*default config*? I cooked one from `rtl_433.conf.example`. 

But the `run_test.py` is so obfuscated, I fail to understand how it finds the files for testing. Besides many tests crashes. E.g. `..\rtl_433.exe -F json -s 250000 -r tests\acurite_3in1\g007_433.92M_250k.cu8`
crashes inside `print_kv_data()`. Another PR ?

**Comment by zuckschwerdt** [comment]
I meant a config at the default location, i.e. loaded by default.
No crash with that line here, perhaps you can trace where the fault is? Or even better PR a fix :)

**Comment by gvanem** [comment]
> I meant a config at the default location, i.e. loaded by default.

Is there a single default location? AFAICS it tries to load `rtl_433.conf` from several places. I have only 1 where `rtl_433.exe` is.

The crash was easy though. `term_get_columns()` returned gibberish when used from Python's `Popen()`. Hence:
```diff
--- a/src/term_ctl.c 2018-12-22 13:39:06
+++ b/src/term_ctl.c 2018-12-28 10:45:24
@@ -169,7 +169,9 @@
     if (!console->hnd || console->hnd == INVALID_HANDLE_VALUE)
        return (80);

-    GetConsoleScreenBufferInfo(console->hnd, &c_info);
+    if (!GetConsoleScreenBufferInfo(console->hnd, &c_info))
+       return (80);
+
```
