### ISSUE TITLE
WH32B issues  - Samples included. 

### ISSUE THREAD

**Issue by slvrscoobie** [merbanan/rtl_433_tests#296]
Fineoffset-WH32B vs. AmbientWeather-WH31E issue from https://github.com/merbanan/rtl_433/issues/971

[Archive 2.zip](https://github.com/merbanan/rtl_433_tests/files/3469934/Archive.2.zip)
Included the samples for the data above.

**Comment by zuckschwerdt** [comment]
Some samples included with d25ef79
