### ISSUE TITLE
[feature request] Limit output to decodings matching a given list of mappings

### ISSUE THREAD

**Issue by curlyel** [merbanan/rtl_433_tests#300]
>The getters need some restructuring anyway. 

_Originally posted by @zuckschwerdt in https://github.com/merbanan/rtl_433_tests/pull/286#issuecomment-526192055_

If this is going to happen, you might consider expanding the getters logic to limit the generated output to just the packets/decodes, where one of the getters map conditions is met, drop all others e.g.:

`get=@0:{20}:code:[123456:REMOTE-A 987654:REMOTE-B 345699:REMOTE-C]:exclusive
`

This would reduce the 'noise' of unwanted decodes being published and prevents potential duplicate decodings from different flex decoders matching on similar settings/timings.

**Comment by zuckschwerdt** [comment]
Can you repost this to rtl_433? 😉

**Comment by curlyel** [comment]
Sure!
Done ;-)
