### ISSUE TITLE
'make test' doesn't work with systems still running python 2

### ISSUE THREAD

**Issue by mcginnly** [merbanan/rtl_433_tests#376]
Hi,
I tried the instructions after cloning the repository and got an error when I ran `make test`. 
Essentially it failed because my system defaults to python2 and couldn't print.
I amended the make file to explicitly use python3 and it worked perfectly:
```
.PHONY: test

test:
	python3 bin/run_test.py -I time --first-line
```

**Comment by Mindavi** [comment]
Yes, we should fix that. I'll make a patch shortly.
