### ISSUE TITLE
Update the GS-WDS07 decode?

### ISSUE THREAD

**Issue by mwolter805** [merbanan/rtl_433_tests#396]
Hello and thanks for your work on this great project! Already using the hertzg/rtl_433_docker container on a Pi to collect the temp and humidity from a few Oregon Scientific sensors and send it via MQTT to Home Assistant. It's working well!

Here's my issue. I'm attempting to add new GS-WDS07 door/window sensors and having a few issues. Would really like to use these sensors as they are cheap (~$4/ea), readily available and can be used for many things in home automation. If we can get these working properly, I'll document everything and share it on the Home Assistant and Reddit forums. Since it uses MQTT it can be used with almost any home automation system, not just Home Assistant. I think many others would like to do this if it's easy and works reliably as the Oregon Scientific decoding does. Found device protocol 30 and the flex decode example for the GS-WDS07 in the conf file but neither seems to work well. 

Protocol 30
This triggers anywhere from 60 to 100 messages from one state change of the sensor. The issue is 60+ messages will cause Home Assistant to trigger for each, causing a huge and unnecessary use of resources for each state change.

Flex Decode
This also triggers 60 to 100 messages via MQTT and there is no consistency to the topics sent. For instance, there is not one topic updated per state change and some topics are updated multiple times.

What I'm hoping to do is have a new protocol or decode that sends only one message per state change of the sensor... IE Open, close or low battery.

I've attached a signal capture and corresponding console output from the GS-WDS07. As you can see there are 21 signals received for one state change (close). Plus a couple of signals are recognized as a different device "Smoke-GS558".

Not really sure where to go from here. Is there anyone that can help with creating a new decode? Or can someone point me in the right direction to work on this myself?

Thanks!

[g001_433.92M_250k-2.cu8.zip](https://github.com/merbanan/rtl_433_tests/files/6792681/g001_433.92M_250k-2.cu8.zip)
[GS-WDS07 output.txt](https://github.com/merbanan/rtl_433_tests/files/6792682/GS-WDS07.output.txt)

**Comment by zuckschwerdt** [comment]
I'll look into the signals and if we can optimized things.

One thing rtl_433 can't deliver is application/use-case specific logic, that might be different for each setup. But you can always post-process the data with something like the scripts in `examples` -- from simple filtering and scaling to aggregating values, keeping state. See https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_custom.py on how this works in general and https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_mqtt_relay.py to relay to MQTT.

**Comment by zuckschwerdt** [comment]
The packets are too far aprt to capture in a single transmission, anyway 60-100 packets are to many to capture in one go anyway.
You need to think up some logic like: if there at least 10 identical messages send a MQTT topic, then suppress more messages for a minute. There is no general way we can handle that in rtl_433 but a relay script will work fine.

**Comment by mwolter805** [comment]
Hello zuckschwerdt, thank you for the info and for looking into this. Some type of rate-limiting would work perfectly for this but I was wondering if it could be resolved before going down that path. I'll look into a script within the rtl_433 container or on the home automation server. 

Thanks again!
