### ISSUE TITLE
Interlogix-Security Tests fail with current rtl_433 content

### ISSUE THREAD

**Issue by obones** [merbanan/rtl_433_tests#446]
Hello,

When I get the current master content from rtl_433 and run the tests, I get the following 4 errors:

```
## Fail with 'tests\interlogix\03\gfile001.cu8':
 values_changed
  * root['switch1']
 Expected: {'model': 'Interlogix-Security', 'subtype': 'motion', 'id': '4aa707', 'battery_ok': 1, 'switch1': 'CLOSED', 'switch2': 'OPEN', 'switch3': 'OPEN', 'switch4': 'OPEN', 'switch5': 'OPEN', 'raw_message': '0955b0'}
  But got: {'model': 'Interlogix-Security', 'subtype': 'motion', 'id': '4aa707', 'battery_ok': 1, 'switch1': 'OPEN', 'switch2': 'OPEN', 'switch3': 'OPEN', 'switch4': 'OPEN', 'switch5': 'OPEN', 'raw_message': '0955b0'}
## Fail with 'tests\interlogix\03\gfile002.cu8':
 values_changed
  * root['switch1']
 Expected: {'model': 'Interlogix-Security', 'subtype': 'motion', 'id': '4aa707', 'battery_ok': 1, 'switch1': 'CLOSED', 'switch2': 'OPEN', 'switch3': 'OPEN', 'switch4': 'OPEN', 'switch5': 'OPEN', 'raw_message': '0955b0'}
  But got: {'model': 'Interlogix-Security', 'subtype': 'motion', 'id': '4aa707', 'battery_ok': 1, 'switch1': 'OPEN', 'switch2': 'OPEN', 'switch3': 'OPEN', 'switch4': 'OPEN', 'switch5': 'OPEN', 'raw_message': '0955b0'}
## Fail with 'tests\interlogix\03\gfile003.cu8':
 values_changed
  * root['switch1']
 Expected: {'model': 'Interlogix-Security', 'subtype': 'motion', 'id': '4aa707', 'battery_ok': 1, 'switch1': 'CLOSED', 'switch2': 'OPEN', 'switch3': 'OPEN', 'switch4': 'OPEN', 'switch5': 'OPEN', 'raw_message': '0955b0'}
  But got: {'model': 'Interlogix-Security', 'subtype': 'motion', 'id': '4aa707', 'battery_ok': 1, 'switch1': 'OPEN', 'switch2': 'OPEN', 'switch3': 'OPEN', 'switch4': 'OPEN', 'switch5': 'OPEN', 'raw_message': '0955b0'}
## Fail with 'tests\interlogix\03\gfile004.cu8':
 values_changed
  * root['switch1']
 Expected: {'model': 'Interlogix-Security', 'subtype': 'motion', 'id': '4aa707', 'battery_ok': 1, 'switch1': 'CLOSED', 'switch2': 'OPEN', 'switch3': 'OPEN', 'switch4': 'OPEN', 'switch5': 'OPEN', 'raw_message': '0955b0'}
  But got: {'model': 'Interlogix-Security', 'subtype': 'motion', 'id': '4aa707', 'battery_ok': 1, 'switch1': 'OPEN', 'switch2': 'OPEN', 'switch3': 'OPEN', 'switch4': 'OPEN', 'switch5': 'OPEN', 'raw_message': '0955b0'}
```

I haven't tried to debug it to figure out if anything is wrong but a quick `git blame` did not show any recent changes in related files.

What would you suggest that I try?

**Comment by zuckschwerdt** [comment]
Maybe it was #2287? That was recent.

I mostly go by the history: https://github.com/merbanan/rtl_433/commits/master/src/devices/interlogix.c

**Comment by zuckschwerdt** [comment]
Yes, confirmed. Are the samples "PET Immune SAW PIR motion sensor" or is the code change wrong?

**Comment by obones** [comment]
Sadly, I don't have access to such a device, so I can't confirm anything here.
It's just that when I try changes to rtl_433, I took the habit of running the tests before submitting them to you.

**Comment by zuckschwerdt** [comment]
We have the errors on all tests/interlogix/03 samples, which state "03-Door contact sensor #1 - trip by opening door".
I'll relay that back to the change author at https://github.com/merbanan/rtl_433/pull/2287

**Comment by yannicklarrivee** [comment]
This is what I got when I ran it on my side:
`python3 bin/run_test.py -I time --first-line
WARNING: Ignoring 'tests/honeywell/RE208/g014_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/RE208/g012_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/RE208/g011_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/RE208/g013_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/RE208/g015_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g007_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g004_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g009_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g002_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g001_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g010_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g003_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g005_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g008_344.975M_250k.cu8'
WARNING: Ignoring 'tests/honeywell/2Gig-DW10/g006_344.975M_250k.cu8'
WARNING: Missing 'tests/idm/IDM/g001_912.6M_2359.3k.cu8'
WARNING: Ignoring 'tests/idm/NetIDM/g012_912.6M_2359.3k.cu8'
WARNING: Ignoring 'tests/idm/NetIDM/g011_912.6M_2359.3k.cu8'
WARNING: Ignoring 'tests/idm/NetIDM/g010_912.6M_2359.3k.cu8'
WARNING: Ignoring 'tests/wec_1502/01/gfile002.cu8'
WARNING: Ignoring 'tests/scmplus/01/g005_912.6M_2359.3k.cu8'
WARNING: Ignoring 'tests/scmplus/01/g003_912.6M_2359.3k.cu8'
WARNING: Ignoring 'tests/scmplus/01/g002_912.6M_2359.3k.cu8'
WARNING: Ignoring 'tests/inkbird/inkbird_ith20r/g001_433.92M_250k.cu8'
WARNING: Ignoring 'tests/inkbird/inkbird_ith20r/g002_433.92M_250k.cu8'
WARNING: Ignoring 'tests/inkbird/inkbird_ith20r/g003_433.92M_250k.cu8'
WARNING: Ignoring 'tests/inkbird/IBS-P01R/g071_433.92M_250k.cu8'
WARNING: Ignoring 'tests/inkbird/IBS-P01R/g026_433.92M_250k.cu8'
WARNING: Ignoring 'tests/inkbird/IBS-P01R/g001_433.92M_250k.cu8'
## Fail with 'tests/cotech/cotech_36-7959/01/g013_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.0, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 190, 'wind_avg_m_s': 0.6, 'wind_max_m_s': 2.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.0, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 190, 'wind_avg_m_s': 0.6, 'wind_max_m_s': 2.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g020_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 241, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 241, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g026_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 126, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 126, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g005_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.0, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 355, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.0, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 355, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g015_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.0, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 188, 'wind_avg_m_s': 1.1, 'wind_max_m_s': 1.7, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.0, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 188, 'wind_avg_m_s': 1.1, 'wind_max_m_s': 1.7, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g009_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.1, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 91, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.1, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 91, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g024_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 57, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 57, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g029_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 84.0, 'wind_dir_deg': 191, 'wind_avg_m_s': 0.1, 'wind_max_m_s': 0.7, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 84.0, 'wind_dir_deg': 191, 'wind_avg_m_s': 0.1, 'wind_max_m_s': 0.7, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g007_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.0, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 269, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.0, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 269, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g001_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.1, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 188, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.1, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 188, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g022_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 299, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.3, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 299, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
## Fail with 'tests/cotech/cotech_36-7959/01/g002_433.92M_1000k.cu8':
 dictionary_item_added
  * root['light_lux']
  * root['uv']
 Expected: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.1, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 189, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'mic': 'CRC'}
  But got: {'model': 'Cotech-367959', 'id': 84, 'battery_ok': 1, 'temperature_F': 73.1, 'humidity': 34, 'rain_mm': 79.2, 'wind_dir_deg': 189, 'wind_avg_m_s': 0.0, 'wind_max_m_s': 0.0, 'light_lux': 69627, 'uv': 251, 'mic': 'CRC'}
WARNING: Ignoring 'tests/adlm_fprf/01/g013_433.92M_250k.cu8'
WARNING: Ignoring 'tests/adlm_fprf/01/g014_433.92M_250k.cu8'
WARNING: Ignoring 'tests/adlm_fprf/01/g011_433.92M_250k.cu8'
WARNING: Ignoring 'tests/adlm_fprf/01/g009_433.92M_250k.cu8'
WARNING: Ignoring 'tests/adlm_fprf/01/g005_433.92M_250k.cu8'
WARNING: Ignoring 'tests/adlm_fprf/01/g007_433.92M_250k.cu8'
WARNING: Ignoring 'tests/adlm_fprf/01/g003_433.92M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g004_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g001_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g005_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g006_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g003_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g007_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g002_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g009_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g010_867.95M_250k.cu8'
WARNING: Ignoring 'tests/IKEA_Sparsnas/01/g008_867.95M_250k.cu8'
WARNING: KlikAanKlikUit-Switch generated 45 false positive(s) in other decoders: {'Proove-Security'}
WARNING: Nexa-Security generated 125 false positive(s) in other decoders: {'KlikAanKlikUit-Switch', 'Proove-Security'}
WARNING: LaCrosse-TX35DTHIT generated 1 false positive(s) in other decoders: {'LaCrosse-TX29IT'}
WARNING: NETIDM generated 1 false positive(s) in other decoders: {'IDM'}
WARNING: Proove-Security generated 67 false positive(s) in other decoders: {'KlikAanKlikUit-Switch', 'Nexa-Security'}
WARNING: Acurite-609TXC generated 6 false positive(s) in other decoders: {'Oregon-SL109H'}
WARNING: Akhan-100F14 generated 193 false positive(s) in other decoders: {'Waveman-Switch'}
WARNING: Rubicson-Temperature generated 5 false positive(s) in other decoders: {'Solight-TE44'}
WARNING: Abarth-124Spider generated 1 false positive(s) in other decoders: {'Renault'}
WARNING: LaCrosse-R3 generated 4 false positive(s) in other decoders: {'LaCrosse-BreezePro'}
WARNING: LaCrosse-R1 generated 2 false positive(s) in other decoders: {'LaCrosse-TH3'}
WARNING: Fineoffset-WH0530 generated 1 false positive(s) in other decoders: {'GT-WT02'}
1819 records tested, 12 have failed
make: *** [test] Error 12`

**Comment by yannicklarrivee** [comment]
No fail on Interlogix device.

**Comment by obones** [comment]
To me, it looks like you updated only one of the two repositories.
