### ISSUE TITLE
Interlogix Saw Sensors

### ISSUE THREAD

**Issue by KevinOberle** [merbanan/rtl_433_tests#74]
https://github.com/merbanan/rtl_433_tests/pull/73

First off, forgive me for something I've probably done wrong. I'm new to rtl_433, git and github. I'm a hobby programmer at best.

I'm looking for help demodulating a set of alarm sensors I have installed in my home. The pull request I just did has all the relevant details in the readme. Thank you very much for your help!

**Comment by merbanan** [comment]
Hi, if you open interlogix/01/gfile001.data as 8bit raw stereo in Audacity you will see that the signal has a preamble and then it uses PPM modulation for 55 pulses and then a long pulse and then 4 more PPM pulses. So try with one of the PPM modulation modes. With that knowledge in mind we can look at the analyser output:

rtl_433 -r rtl_433_tests/tests/interlogix/01/gfile001.data -A

Gap width distribution:
 [ 0] count:   41,  width:    32 [29;34]	( 128 us)
 [ 1] count:   18,  width:    62 [60;65]	( 248 us)

Here we can see that we have 2 different gaps detected. And there is a multiple of 2 between them in us. (128*2=248) So the best decision limit to set is a value in the middle. (128+248/2)

So change to that and you should get a consistent bit buffer.

**Comment by merbanan** [comment]
If you still need help ask on the mailing list or open a ticket on the rtl_433 repo.
